version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: densy_db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    container_name: densy_app
    build:
      context: .
      dockerfile: .dockerfile
    restart: always
    ports:
      - "${CLIENT_PORT}:3000"
      - "${SERVER_PORT}:4000"
    env_file:
      - ./server/.env
      - ./client/.env
    volumes:
      - ./server/uploads:/app/server/uploads  
    depends_on:
      - db

  nginx:
    container_name: densy_nginx
    image: nginx:1.13.0-alpine
    restart: always
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db_data:
