services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins.dockerfile
    container_name: densy_jenkins
    ports:
      - "8027:8080"
      - "8028:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_HOST_PATH}:/workspace/TEAM6-DENSY 
    restart: always
    user: root
    environment:
      DOCKER_COMPOSE_VERSION: v2.21.0   

volumes:
  jenkins_home: