services:
  db:
    image: mysql:latest
    container_name: densy_db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - densy_network

  app:
    container_name: densy_app
    build:
      context: .
      dockerfile: .dockerfile
    restart: always
    environment:
      NODE_ENV: production
    env_file:
      - ./server/.env
      - ./client/.env
    volumes:
      - ./server/uploads:/app/server/uploads
    depends_on:
      - db
    networks:
      - densy_network

  nginx:
    container_name: densy_nginx
    image: nginx:1.13.0-alpine
    restart: always
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_SSL_PORT}:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - densy_network

volumes:
  db_data:


networks:
  densy_network:
    driver: bridge
