version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: densy_db
    environment:
      MYSQL_DATABASE: densy_data
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  client:
    container_name: densy_client
    build:
      context: ./client
      dockerfile: client.dockerfile
    image: client
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    env_file:
      - ./client/.env
    depends_on:
      - server

  server:
    container_name: densy_server
    image: server
    restart: always
    env_file:
      - ./server/.env
    build:
      context: ./server
      dockerfile: server.dockerfile
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "mysql://root:12345@db:3306/densy_data"
    depends_on:
      - db
  nginx:
    container_name: densy_nginx
    image: nginx:1.13.0-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - server

volumes:
  db_data:
