services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: client.dockerfile
    image: client
    restart: always
    # ports:
    #   - "3000:3000"
    # environment:
    #   - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - server

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: server.dockerfile
    image: server
    restart: always
    env_file:
      - ./server/.env.server
    # ports:
    #   - "4000:4000"
    environment:
    #   # - DATABASE_URL=mysql://user:password@db:3306/densy_proto
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: densy_data
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: verysecret
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=caching_sha2_password"
      ]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    ports:
      - "8028:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: verysecret

  nginx:
    container_name: nginx
    image: nginx:1.13.0-alpine
    restart: always
    ports:
      - "8027:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - server


volumes:
  db_data: